name: Sync Readme.io

on:
    push:
        branches:
            - "master"
            - "readme-sync-tests-15032022"

jobs:
    Sync:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1        
            - name: Sync Checkout API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Checkout\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8be
            - name: Sync orders API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Orders\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8b9
            - name: Sync Master Data API - v2
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Master\ Data\ API\ -\ v2.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8ba
            - name: Sync Master Data API - v1
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ MasterData\ API\ -\ v10.2.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8ce
            - name: Sync Session Manager
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Session\ Manager\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8bb
            - name: Sync License Manager API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ License\ Manager\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8bc
            - name: Sync CMS API (Change URI Schema)
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi CMS\ -\ Change\ URI\ Schema.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8bf
            - name: Sync Customer Credit API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Customer\ Credit\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c1
            - name: Sync Giftcard Hub API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ GiftCard\ Hub\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c2
            - name: Sync Giftcard API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Giftcard\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c3
            - name: Sync Giftcard Provider Protocol API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Giftcard\ Provider\ Protocol.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c4
            - name: Sync Payment Provider Protocol API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Payment\ Provider\ Protocol.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c6
            - name: Sync Payments Gateway API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Payments\ Gateway\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c7
            - name: Sync Pricing API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi VTEX\ -\ Pricing\ API.json --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c8
            - name: Sync Recurrence API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Recurrence (v1 - deprecated).json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8ca
            - name: Sync Subscriptions API - v2
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Subscriptions API (v2).json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8cc
            - name: Sync Subscriptions API - v3
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Subscriptions API (v3).json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8f3
            # - name: Sync Sugestions API # Reference does not exist in Readme
            #   uses: readmeio/rdme@7.0.1
            #   with:
            #     rdme: openapi 'VTEX - Suggestions API.json' --key=${{ secrets.README_API_KEY }} --id=5eb562add9eb40005e689401
            - name: Sync VTEX DO API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - VTEX Do API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8cd
            - name: Sync Antifraud Provider API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Antifraud Provider API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8cf
            - name: Sync VTEX Tracking API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Tracking.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8e8
            # - name: Sync VTEX Tracking API - v1.1 # File does not exist
            #   uses: readmeio/rdme@7.0.1
            #   with:
            #     rdme: openapi 'VTEX - Tracking v1.1.json' --key=${{ secrets.README_API_KEY }} --id=5eff5672f1055500110af826
            - name: Sync Message Center API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Message Center API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8ef
            - name: Sync Policy Engine API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Policies System API.json' --key=${{ secrets.README_API_KEY }} --id=6091a6fd8359b80052674552
            - name: Sync Marketplace Protocol API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Marketplace Protocol.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8e9
            - name: Sync Marketplace APIs
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Marketplace APIs.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8ec
            - name: Sync Pricing Hub API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Pricing Hub.json' --key=${{ secrets.README_API_KEY }} --id=6079c44a5be63500109ceb01
            - name: Sync Profile System API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Profile System.json' --key=${{ secrets.README_API_KEY }} --id=620ec1ba4e4622003c8185ae
            - name: Sync Promotions & Taxes API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Promotions & Taxes API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c9
            - name: Sync Logistics API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Logistics API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8c5
            - name: Sync Catalog API
              uses: readmeio/rdme@7.0.1
              with:
                rdme: openapi 'VTEX - Catalog API.json' --key=${{ secrets.README_API_KEY }} --id=6037ec28bea7b903b303e8bd
     

    # Sync_CLI:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@v1
    #         - uses: actions/setup-node@v1
    #           with:
    #               node-version: "12.x"
    #         - name: Install RDME
    #           run: npm install -g rdme
    #
    #         - name: Sync Pricing Hub API
    #           run: rdme openapi 'VTEX - Pricing Hub.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6079c44a5be63500109ceb01
    #         - name: Sync Search API
    #           run: rdme openapi 'VTEX - Search API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8cb
