name: Sync Readme.io

on:
    push:
        branches:
            - "master"

jobs:
    Sync:
        runs-on: ubuntu-latest

        steps:
            - name: Sync Master Data V2 schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8ba"
                  api-file-path: "VTEX - Master Data API - v2.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Master Data V1 schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8ce"
                  api-file-path: "VTEX - MasterData API - v10.2.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Session Manager schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8bb"
                  api-file-path: "VTEX - Session Manager API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync License Manager schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8bc"
                  api-file-path: "VTEX - License Manager API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync 'Change url schema' schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8bf"
                  api-file-path: "CMS - Change URI Schema.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Customer Credit API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c1"
                  api-file-path: "VTEX - Customer Credit API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Giftcard Hub API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c2"
                  api-file-path: "VTEX - GiftCard Hub API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Giftcard API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c3"
                  api-file-path: "VTEX - Giftcard API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Giftcard Provider Protocol schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c4"
                  api-file-path: "VTEX - Giftcard Provider Protocol.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Payment Provider Protocol schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c6"
                  api-file-path: "VTEX - Payment Provider Protocol.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Payments Gateway API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c7"
                  api-file-path: "VTEX - Payments Gateway API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Pricing API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8c8"
                  api-file-path: "VTEX - Pricing API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Recurrence schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8ca"
                  api-file-path: "VTEX - Recurrence (v1 - deprecated).json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Subscriptions API (v2) schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8cc"
                  api-file-path: "VTEX - Subscriptions API (v2).json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Subscriptions API (v3) schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8f3"
                  api-file-path: "VTEX - Subscriptions API (v3).json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            #     - name: Sync Suggestions API schema
            #       uses: readmeio/github-readme-sync@1.0.3
            #       with:
            #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
            #         readme-api-id: '5eb562add9eb40005e689401'
            #         api-file-path: 'VTEX - Suggestions API.json'
            #         readme-api-key: '${{ secrets.README_API_KEY }}'
            #         readme-api-version: '2.1'
            - name: Sync Vtex DO API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8cd"
                  api-file-path: "VTEX - VTEX Do API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Vtex Antifraud Provider schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8cf"
                  api-file-path: "VTEX - Antifraud Provider API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync VTEX Tracking API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8e8"
                  api-file-path: "VTEX - Tracking.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            #    - name: Sync VTEX Tracking API version 1.1 schema
            #      uses: readmeio/github-readme-sync@1.0.3
            #      with:
            #        repo-token: '${{ secrets.GITHUB_TOKEN }}'
            #        readme-api-id: '5eff5672f1055500110af826'
            #        api-file-path: 'VTEX - Tracking v1.1.json'
            #        readme-api-key: '${{ secrets.README_API_KEY }}'
            #        readme-api-version: '2.1'
            - name: Sync Message Center API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8ef"
                  api-file-path: "VTEX - Message Center API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Policy Engine API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6091a6fd8359b80052674552"
                  api-file-path: "VTEX - Policies System API.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Marketplace Protocol schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8e9"
                  api-file-path: "VTEX - Marketplace Protocol.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Marketplace API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6037ec28bea7b903b303e8ec"
                  api-file-path: "VTEX - Marketplace APIs.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Pricing Hub API schema
              uses: readmeio/github-readme-sync@1.0.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  readme-api-id: "6079c44a5be63500109ceb01"
                  api-file-path: "VTEX - Pricing Hub.json"
                  readme-api-key: "${{ secrets.README_API_KEY }}"
                  readme-api-version: "2.1"
            - name: Sync Profile System API
              uses: readmeio/github-readme-sync@1.0.3
              with:
                   repo-token: "${{ secrets.GITHUB_TOKEN }}"
                   readme-api-id: "620ec1ba4e4622003c8185ae"
                   api-file-path: "VTEX - Profile System.json"
                   readme-api-key: ${{ secrets.README_API_KEY }}
                   readme-api-version: "2.1"

    # EXAMPLE TEMPLATE -- Copy the example below and replace the indicated values with your information
    # 
    #      - name: Sync Template API # Replace "Template" with the API name
    #        uses: readmeio/github-readme-sync@1.0.3
    #        with:
    #             repo-token: '${{ secrets.GITHUB_TOKEN }}' # DON'T MODIFY -- Allows us to get the contents of your specification file
    #             readme-api-id: '123456' # ID of the API on Readme.io. You can find it on the API Definitions tab on Readme.io's dashboard
    #             api-file-path: 'VTEX_TEMPLATE.json' # Name of the API specification JSON file. The file must be on the root folder of the repository
    #             readme-api-key: ${{ secrets.README_API_KEY }} # DON'T MODIFY -- Readme.io API key
    #             readme-api-version: '2.1' # Readme.io version to sync to

    Sync_CLI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install RDME
              run: npm install -g rdme
            - name: Sync Promotions & Taxes API
              run: rdme openapi 'VTEX - Promotions & Taxes API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8c9
            - name: Sync Orders API
              run: rdme openapi 'VTEX - Orders API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8b9
            - name: Sync Logistics API
              run: rdme openapi 'VTEX - Logistics API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8c5
            - name: Sync Catalog API
              run: rdme openapi 'VTEX - Catalog API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8bd
            - name: Sync Checkout API
              run: rdme openapi 'VTEX - Checkout API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8be
            - name: Sync Pricing Hub API
              run: rdme openapi 'VTEX - Pricing Hub.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6079c44a5be63500109ceb01
            - name: Sync Search API
              run: rdme openapi 'VTEX - Search API.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=6037ec28bea7b903b303e8cb

# EXAMPLE TEMPLATE -- Copy the example below and replace the indicated values with your information
#
#           - name: Sync Template API  # Replace "Template" with the API name
#             run: rdme openapi 'VTEX_TEMPLATE.json' --key=${{ secrets.README_API_KEY }} --version=v2.1 --id=123456
# 
#           Replace 'VTEX_Template.json' with the name of the API specification JSON file between ' '. The file must be on the root folder of the repository.
#           DON'T MODIFY the 'key' value, it is the Readme.io API key.
#           The 'version' is the Readme.io version to sync to.
#           Replace the 'id' value with the ID of the API on Readme.io. You can find it on the API Definitions tab on Readme.io's dashboard.
